name: Prod branch
on:
  workflow_dispatch:
    inputs:
      version_tag:
        type: string
        description: "Specify app version. Format: x.x.x"
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "code: check out code"
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: echo
        run: echo ${{ steps.extract_branch.outputs.branch }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ inputs.version_tag }}
          draft: false
          prerelease: false
